apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: alexsts/cashflow-accounts
      context: accounts
      docker:
        dockerfile: Dockerfile
    - image: alexsts/cashflow-tasks
      context: tasks
      docker:
        dockerfile: Dockerfile

