apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: cashflow.dev
      http:
        paths:
          - path: /api/accounts/?(.*)
            pathType: Prefix
            backend:
              service:
                name: accounts-clusterip-srv
                port:
                  number: 80
          - path: /api/(promotion|income)/tasks/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tasks-clusterip-srv
                port:
                  number: 80
          - path: /api/money/?(.*)
            pathType: Prefix
            backend:
              service:
                name: money-clusterip-srv
                port:
                  number: 80
          - path: /api/moderation/?(.*)
            pathType: Prefix
            backend:
              service:
                name: moderation-clusterip-srv
                port:
                  number: 80