name: deploy-accounts

on:
  push:
    branches:
      - main
    paths:
      - 'accountservice/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - name: Deploy to Dockerhub  
      - run: cd accountservice && docker build -t alexsts/cashflow-accounts . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alexsts/cashflow-accounts