name: deploy-money

on:
  push:
    branches:
      - master
    paths:
      - 'money/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 
      - run: cd money && docker build -t alexsts/cashflow-money . 
      - name: Deploy to Dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alexsts/cashflow-money