name: tests-account

on: 
  pull_request:
    paths: 
      - 'accountservice/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: cd accountservice && dotnet restore
      - name: Build
        run: cd accountservice && dotnet build
      - name: Test with the dotnet CLI
        run: cd accountservice && dotnet test
